### List all tasks
GET {{baseURI}}/api/tasks

### Get task by ID
GET {{baseURI}}/api/tasks/01J0BKVT74WV0FVBPGYKWRQ55Y

### Get non-existent task
GET {{baseURI}}/api/tasks/00000000000000000000000000

### Get task by project
GET {{baseURI}}/api/tasks/by-project/01J0EVKS52H6MSM8VY7BRTK2CH/2024-01-01


### Create task
POST {{baseURI}}/api/tasks
Content-Type: application/json

{
  "project": "01J0EVKS52H6MSM8VY7BRTK2CH",
  "title": "Task 2",
  "date": "2024-01-01",
  "time": "12:00"
}

### Update task
PUT {{baseURI}}/api/tasks/01HZYE23WYAP6RXNY45NEG6DGR
Content-Type: application/json

{
  "title": "Project 1"
}

### Update task
PATCH {{baseURI}}/api/tasks/01HZYE23WYAP6RXNY45NEG6DGR
Content-Type: application/json

{
  "description": "Description of Project 1"
}

### Delete task
DELETE {{baseURI}}/api/tasks/01J0F33CH8NBW9VZVFCDQ95BQH

### List all tasks – custom implementation
GET {{baseURI}}/api/all-tasks

